#!/usr/bin/env python3
import os
from pathlib import Path
import subprocess
from appliance_state import CONTROL, read, write

write(Path('/etc/netplan/90-cybex-james.yaml'), read(CONTROL / 'netplan-approved.json'), mode=0o600, group=0)
subprocess.run(['/usr/lib/cybex-james/cybex-james-netplan-activate'], check=True,
               env={**os.environ, 'CYBEX_NETWORK_RENDER_ONLY': '1'})
